CREATE TABLE IF NOT EXISTS projects(
    id integer Primary Key Generated by Default as IDENTITY,
    name text Not Null Check (name <> ''),
    priority integer Not Null,
    description text,
    deliverydate date Not Null
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer Primary Key Generated by Default as IDENTITY,
    name text Not Null Check (name <> ''),
    done Boolean,
    projectId integer references projects(id)
);require

insert into projects (name,priority,description,deliverydate) 
values ('make a web app',1,'using Javascript','2019-05-12');

insert into tasks (name ,done ,projectId)
values ('Download Vuejs',false,1);
